DROP TABLE IF EXISTS d_ah_news, d_ah_news_categories;

CREATE TABLE `d_ah_news` (
  ID             INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DATE_CREATE    DATETIME,
  DATE_INSERT    DATETIME,
  DATE_FINISHED    DATETIME,
  CREATED_BY     INT,
  MODIFIED_BY    INT,
  TITLE          VARCHAR(255)
);

CREATE TABLE `d_ah_packages` (
  ID             INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  PACKAGE_ID     INT NOT NULL,
  DATE_INSERT    DATETIME,
  TITLE          VARCHAR(255)
);